liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        avatar:
            quality: 90
            filters:
                thumbnail: { size: [200, 200], mode: outbound }