liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        food_list:
            quality: 100
            filters:
                thumbnail: { size: [214, 214], mode: outbound }
                
        banner_homepage_thumb:
            quality: 100
            filters:
                thumbnail: { size: [250, 100], mode: outbound }
                
        left_banner:
            quality: 100
            filters:
                thumbnail: { size: [236, 100], mode: outbound }
                
        othernews_thumb:
            quality: 100
            filters:
                thumbnail: { size: [110, 83], mode: inbound }
                
        news_thumb:
            quality: 100
            filters:
                thumbnail: { size: [260, 160], mode: outbound }
                
        gallery:
            quality: 100
            filters:
                thumbnail: { size: [214, 214], mode: outbound }