kampong_site:
    resource: "@KampongSiteBundle/Resources/config/routing.xml"
    prefix:   /

aseagle_front:
    resource: "@AseagleFrontBundle/Resources/config/routing.xml"
    prefix:   /front

aseagle_admin:
    resource: "@AseagleAdminBundle/Resources/config/routing.xml"
    prefix:   /admin

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
    prefix:   /admin
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    